First version of entity auditing api
intelie/gitbook-platform pull request #20
Opened 2023-06-16 14:57 UTC by RTardelliGarcia

Add a new page to describe the Entity Audit feature in the **Features** topics with a more general approach to the subject. In addition, there is a more developer-oriented page in the **Developers/Back-end API** area explaining the solution in more detail.

2023-06-16 18:59 UTC, hugomcs requested changes

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +### EntityAudit as an database record
EntityAudit as **a** database record

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +This endpoint lists all `EntityAudits` of a specific entity, e.g. `{base-Url}/rest/entity-audit/list/perspective` will return a list of `EntityAudits` of the entity `Perspective`.
...a specific entity**.** E.g. ...

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +This endpoint lists all `EntityAudits` of a specific entity identified by *id*, e.g. `{base-Url}/rest/entity-audit/list/perspective/8` will return a list of `EntityAudits` of the entity `Perspective`
... identified by *id*. E.g. ...

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +This endpoint retrieves the entity content from a `EntityAudit`. It is used to obtain the entity stored by a `EntityAudit`, e.g. `{base-Url}/rest/entity-audit/100` will return the entity content of t
... stored by a `EntityAudit`**.** E.g. ...

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
**Getting** an EntityAudit **that represents** a delete operation will return a BAD_REQUEST. As explained before**,** EntityAudits of delete operations do not hold an entity content.

2023-06-16 18:59 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
I think It's worth to include a paragraph explaining the steps needed to rollback an entity state.

2023-06-16 19:12 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +Live supports storing an `EntityAudit` in two forms: a _database record_ and/or an _event_ depending on the configuration set in the general system settings.
That is the spot where I would like to add the image of the configuration card. Do you think we should change the text? I am trying to avoid being repetitive.

2023-06-16 19:12 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +An **Entity Audit** represents a write operation of an **Live** entity that was listened by a Hibernate Listener and transformed into a new entity called `EntityAudit` about this operation and the ne
Good suggestions

2023-06-16 19:15 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +- *The entity should not come from a call skipping audit*. This is used when the client calls the API method `Live.data().installEntities()` flagging to avoid auditing entities in an bulk entity crea
good catch

2023-06-16 19:18 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +As said before, if the feature is enabled in the system configurations, the write operations of entities will be stored containing the current version of the entity in json format, e.g. the `Plugin`
Starting a sentence with "E.g." seems to be wrong to me. Are you sure about that?

2023-06-16 19:23 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +With this information in hand, it is possible to list the different versions of an entity's field (or all fields) and return to a past value.
What do you think of: 
```suggestion
With this information in hand, it is possible to list the different versions of an entity's field (or all fields) and roll it back to a previous version.
```

I am testing the suggestion here, but the change was: ... , and roll it back to a **previous** version.

2023-06-16 19:27 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +This endpoint lists all `EntityAudits` of a specific entity, e.g. `{base-Url}/rest/entity-audit/list/perspective` will return a list of `EntityAudits` of the entity `Perspective`.
Again, starting a sentence with "E.g." seems to be wrong to me. Are you sure about that?

2023-06-16 19:27 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +This endpoint lists all `EntityAudits` of a specific entity identified by *id*, e.g. `{base-Url}/rest/entity-audit/list/perspective/8` will return a list of `EntityAudits` of the entity `Perspective`
Again, starting a sentence with "E.g." seems to be wrong to me. Are you sure about that?

2023-06-16 19:28 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +This endpoint retrieves the entity content from a `EntityAudit`. It is used to obtain the entity stored by a `EntityAudit`, e.g. `{base-Url}/rest/entity-audit/100` will return the entity content of t
Again, starting a sentence with "E.g." seems to be wrong to me. Are you sure about that?

2023-06-16 19:33 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
Well, we showed how to get an older version of an entity. It seems to me to be clear enough that the client should save the new state if he wants it. Do you think that can be a misunderstanding with it?

2023-06-16 19:36 UTC, RTardelliGarcia commented on features/entity-audit.md
> +**Intelie Live** provides a mechanism to enable auditing writing operations with Entities as database records or as events. This feature is not mandatory and the admin need to turn it in the **Genera
I agree with the text. I think the screenshot of the configuration card will fit here.

2023-06-16 19:41 UTC, RTardelliGarcia reviewed
Some changes were made after @hugomc 's review. Some discussions are still  opened

2023-06-16 19:41 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +Live supports storing an `EntityAudit` in two forms: a _database record_ and/or an _event_ depending on the configuration set in the general system settings.
I think it's a good idea for you to reference the image in the text, and leave a placeholder. This way, it will be easier to add the image later.

2023-06-16 19:44 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +This endpoint lists all `EntityAudits` of a specific entity, e.g. `{base-Url}/rest/entity-audit/list/perspective` will return a list of `EntityAudits` of the entity `Perspective`.
You are right. It's ok as it is.

2023-06-16 19:46 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
Just a short sentence saying that he can use that older entity, and call a save on the related resource, if he wants to rollback the state.

2023-06-19 13:48 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +Live supports storing an `EntityAudit` in two forms: a _database record_ and/or an _event_ depending on the configuration set in the general system settings.
I asked in the Backend chapter meeting if anyone has ever done this and some people suggested referencing the image directly from the `.gitbook/assets` folder.

2023-06-19 13:53 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
Fair enough. What do you think of: ``` If it were the case, the user can use the result of this method to roll back parts or all of the current version of an entity.```?

2023-06-19 14:15 UTC, AllanSouza23 commented on developers/backend-api/entity-audit.md
> +![configuration image](<../.gitbook/assets/entity_audit_config.png>)
Maybe  `![configuration image](<../../.gitbook/assets/entity_audit_config.png>)`?

2023-06-19 15:56 UTC, RTardelliGarcia commented on developers/backend-api/entity-audit.md
> +![configuration image](<../.gitbook/assets/entity_audit_config.png>)
Yes. Good catch! There is one more level

2023-06-19 19:56 UTC, hugomcs commented on developers/backend-api/entity-audit.md
> +{% hint style="warning" %} Get an EntityAudit representing a delete operation will return a BAD_REQUEST. As explained before EntityAudits of delete operations do not hold an entity content {% endhint
If **needed**, the user can use the result of this method to roll back parts or all of the current version of an entity **by calling the save method on the related resource class.**

2023-06-19 21:01 UTC, merged